### ISSUE TITLE
SAML Support - Is it still Preview else update documentation

### ISSUE THREAD

**Issue by rsrinivasanhome** [azure-ad-b2c/saml-sp#3]
My understanding is SAML supported as part of custom policies part of Azure AD B2C and no longer a preview feature
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview-custom

https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15334323-saml-protocol-support
Could you please confirm and update the documentation

**Comment by JasSuri** [comment]
Integration (federation) of SAML & OpenId IdPs with Identity Experience Framework are Generally Available. This still requires that the Application uses OpenId Connect to talk to AAD B2C. AAD B2C can then talk OpenId or SAML to an external IdP.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-developer-notes-custom

Support for SAML Relying Parties (where the App sends a SAML Request to B2C and expects a SAML response back), is in private preview and unsupported. The samples in this repo are for SAML RP.
