### ISSUE TITLE
Error AADB2C90022 when requesting metadata

### ISSUE THREAD

**Issue by phunkyg** [azure-ad-b2c/saml-sp#4]
I have followed the guide and pre-requisites as closely as possible but all custom configurations that pass upload verification seem to end in the same result:

> Sorry, but we're having trouble signing you in.
> We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, please try again.
> Correlation ID: f3a4e59f-ab87-42e0-a283-7ccc810cb48c
> Timestamp: 2019-07-01 12:48:56Z
> AADB2C90022: Unable to return metadata for the policy 'B2C_1A_signup_signin_SAML' in tenant 'spaweb.onmicrosoft.com'.

Application Insights is configured for my test, but no entries in the 'traces' table are added when this error is experienced.

I understand that this error code relates to configuration errors in one or more of the XML files.
Is there a way to gain further debugging information to find my configuration problem?

**Comment by phunkyg** [comment]
I believe I have resolved this issue by repeating all steps. The errant step seemed to be the creation of a self-signed certificate.
For whatever reason, replacing this cert removed that particular error code.

It seems this error code can relate to a number of reasons that are hard to diagnose. Could these messages be improved to indicate at which step the problem occurs?

**Comment by JasSuri** [comment]
Since this is in private preview, the error messages are still being worked on. Rest assured that proper error handling would be enabled as this moves into public preview and general availability.

The error was that we could not find a valid certificate in the B2C policy key store for 'Saml2AssertionIssuer', potentially it was expired.

**Comment by jakub-bochenski** [comment]
> Rest assured that proper error handling would be enabled as this moves into public preview and general availability.

Here I am, 2 years later with the same useless error message

Thanks Microsoft!

![Screenshot_20210322_173618](https://user-images.githubusercontent.com/2794994/112025144-2c700b00-8b35-11eb-98d7-3b1646691299.png)

**Comment by JasSuri** [comment]
Your error is:
`No valid certificate found in key container with id 'SamlMessageSigning' for technical profile: 'Saml2AssertionIssuer'`

If you used a self sign cert in windows, make sure to add the `-keyusage sign` parameter.

**Comment by jakub-bochenski** [comment]
Thanks, so I need to enable Application Insights to be able to see this error?

**Comment by jakub-bochenski** [comment]
BTW I've used the Azure Web interface option to generate a "RSA" key for "signing", should that be a proper type?

**Comment by DukaDima** [comment]
I also faced the same problem. 
I use Azure AD B2C for SPA on Next JS and Next-Auth. 
-------------------------------------------------------------
Sorry, but we're having trouble signing you in.
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, please try again.
Correlation ID: 5c118fd1-bd32-4ccf-a870-6dde627e8536
Timestamp: 2022-06-02 18:10:54Z
AADB2C99059: The supplied request must present a code_challenge
---------------------------------------------------------------
i cannot find the solution.

**Comment by aliah** [comment]
I am facing the same issue:

**Correlation ID: 8292be67-107a-48ef-8be8-512e9e1fe944
Timestamp: 2024-12-22 01:24:47Z
AADB2C90022: Unable to return metadata for the policy 'B2C_1A_signup_signin_members' in tenant 'la****.onmicrosoft.com'.**

@JasSuri , can you please let me know the error? I used the 'Generate' option to create the signing certificate directly from within the portal. I selected RSA and "Signatures" as the purpose. 

Thank you.

**Comment by aliah** [comment]
> BTW I've used the Azure Web interface option to generate a "RSA" key for "signing", should that be a proper type?
> 
> OpenSSL to the rescue
> 
> ```
> $ openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj '/CN=yourappname.yourtenant.onmicrosoft.com'
> $ openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem
> ```

I used the web interface 'Generate' option as well and I got the same error.
