### ISSUE TITLE
Accessing custom user attributes

### ISSUE THREAD

**Issue by sjthompsonengl** [azure-ad-b2c/saml-sp#5]
I've defined a custom user attribute which I want to use as an OutputClaim in a SAML-SP request. I cannot get the policy to upload because of the following errors:

Persisted Claim 'orgName' is not supported in Azure Active Directory Provider technical profile 'AAD-UserWriteProfileUsingObjectId' of policy <PolicyName>

Output Claim 'orgName' is not supported in Azure Active Directory Provider technical profile 'AAD-UserReadUsingObjectId' of policy <PolicyName>

I've tried following this article as a reference: https://medium.com/the-new-control-plane/working-with-custom-attributes-in-azure-ad-b2c-custom-policies-fae1454b12bf

**Comment by JasSuri** [comment]
That is a custom attribute, so it must be called extension_orgname when writing to the directory.


‘’’xml
  <PersistedClaim ClaimTypeReferenceId="Orgname" PartnerClaimType="extension_orgname" />’’’
